name: Blog CI/CD
permissions:
  contents: write
# 触发条件：在 push 到 hexo-blog-backup 分支后触发
on:
  workflow_dispatch:
  push:
    branches: 
      - src
      - main


jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        
    - name: Cache node modules
      # 设置包缓存目录，避免每次下载
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
          ~/.npm
        key: ${{ runner.os }}-node-v3-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        
    - name: hexo run
      run: |
        hexo clean
        hexo g
        
    - name: Deploy to Github Pages
      env:
        GIT_NAME: lblk
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/lblk/single_site.git
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GIT_NAME:$GH_TOKEN@$REPO" master:blog
